# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         p5-WWW-iTunesConnect
version:      1.14
version_from: lib/WWW/iTunesConnect.pm
installdirs:  site
requires:
    HTML::Form:                    0
    HTML::Tree:                    0
    IO::Uncompress::Gunzip:        0
    LWP:                           5.829
    Net::SSLeay:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
